site_name: VaaniAI

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Technical Design: technical_design.md
  - Local Setup: setup.md

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
